name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm ci
    - name: Check Types
      run: npx tsc --noEmit
    - name: Check Code
      run: npx @biomejs/biome ci src
    - name: Run tests
      run: npm test

